### ISSUE TITLE
Cloning the YAPE image fails

### ISSUE THREAD

**Issue by waltgh** [murrayo/yape#22]
I am following the directions on cloning the YAPE image but the clone fails at the following line:
  Downloading https://files.pythonhosted.org/packages/b7/93/b544dd08092b457d88e10fc1e0989d9397fd32ca936fdfcbb2584178dd2b/pandas-0.25.3.tar.gz (12.6MB)
    ERROR: Command errored out with exit status 1:

Any ideas?  I can access the file directly from my computer but it appears the download fails.

**Comment by murrayo** [comment]
hi, The component that is failing is 'pandas' which is part of python. So it's possible it will work if you try again. If its a version issue, you need to ensure you are running a Python 3.x. Ideally 3.7 as per the README. I recommend anaconda.
Because of issues like this  (e.g. python versions etc)  I recommend using docker. However, it should still work OK on installed python.
